### ISSUE TITLE
Reflection about traduction

### ISSUE THREAD

**Issue by niltied** [hugo-toha/guides#234]
Re @hossainemruz,

Suppose I want to start translating the guide into French. How should I go about it ?

Today, the `content/posts` directory doesn't have an `en` or `fr` directory to differentiate articles from one language to another. 

Should I conclude that it would be necessary to create a complete clone of the original repository and replace the English content with French content ? This would not be practical as someone wanted to offer a German or Spanish translation for example, there would be as many repositories of the guide as there are language 🤔🤨.

Last question : If someone updates the original doc, how can I detect this and report the change to another language ?  

Do you have an opinion ?  Thank you by advance for your feedback.

**Comment by hossainemruz** [comment]
Hi, you just have to add another markdown with respective language code. For example, if your post markdown is called `my-post.md`. For, French translation just add another markdown with `my-post.fr.md`.

Here is an example: https://github.com/hugo-toha/hugo-toha.github.io/tree/main/content/posts/introduction

Make sure you have enabled multiple language support.
https://github.com/hugo-toha/hugo-toha.github.io/blob/2c32a26d220702b31dd52631bbfa8e9ab961ac19/config.yaml#L22

**Comment by niltied** [comment]
Re,

Your solution answers my first question very well 🤗. This is very good news because I see that translating posts is technically easy. 

On the other hand, we have no means of controlling the tracking of a translation between 2 markdown files apart from the modification date. Exact ?

**Comment by hossainemruz** [comment]
Yes. There is know way to detect if the original doc and translated doc are in-sync or not.

**Comment by niltied** [comment]
Right. You answered all of my questions and I have a technical solution to translate and contribute to toha.
I just need to find time to work on it now.

You can close this issue now. Thank you, see you later.

**Comment by hossainemruz** [comment]
Sure. A contribution will be really appreciated.
