### ISSUE TITLE
Alert code example in shortcode page

### ISSUE THREAD

**Issue by niltied** [hugo-toha/guides#241]
Hi @hossainemruz,

# Context

When you read the [shortcodes](https://toha-guides.netlify.app/posts/shortcodes/) page. We can see the different alert blocks available on the page. But there are no code examples associated with each block on the post.

This is not practical, the visitor is forced to go to the git repository to see the code examples.

# Solution possible

For each alert block, put the associated shortcode directly on the post.

# Note 

Note that this development is valid for the entire rest of the page.

**Comment by hossainemruz** [comment]
Thank you for bringing it up. We have the code on the markdown file [here](https://github.com/hugo-toha/guides/blob/main/content/posts/shortcodes/index.md). However, I agree that we should show the code in the rendered post.

**Comment by niltied** [comment]
OK @hossainemruz, i will update post in English language and French too. New Merge Request soon.

**Comment by hossainemruz** [comment]
Thank you.

**Comment by hossainemruz** [comment]
Completed in #247

**Comment by niltied** [comment]
Thank @hossainemruz. Good jib. It's better now.
