### ISSUE TITLE
config.yaml renamed to hugo.yaml

### ISSUE THREAD

**Issue by tcarreira** [hugo-toha/guides#301]
On the guide https://toha-guides.netlify.app/posts/update-v3-to-v4/#6-update-the-configyaml-file there is an instruction:

>  you can check the sample [config.yaml](https://github.com/hugo-toha/hugo-toha.github.io/blob/main/config.yaml)

that should be renamed to 
> you can check the sample [hugo.yaml](https://github.com/hugo-toha/hugo-toha.github.io/blob/main/hugo.yaml) (previously config.yaml)

I'm not 100% sure about the parenthesis though, waiting for comments.
There are probably more references like this on other posts as well

**Comment by BernatBC** [comment]
Hi @tcarreira, thank you for pointing it out. You're right, `config.yaml` was renamed to `hugo.yaml`. For me, `previously config.yaml` looks good.

**Comment by BernatBC** [comment]
Hi @hossainemruz, what do you think is best?
- Replace all occurrences of `config.yaml` to `hugo.yaml`
- Replace only the references to the file in `hugo-toha.github.io`

**Comment by hossainemruz** [comment]
> Hi @hossainemruz, what do you think is best?
> 
> * Replace all occurrences of `config.yaml` to `hugo.yaml`
> * Replace only the references to the file in `hugo-toha.github.io`

Let's go with the first option. Replace all occurrences of `config.yaml` with `hugo.yaml`
