### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by alnutile** [hugo-toha/guides#34]
You do not mention tags in your docs but they are pretty easy to add.

```
        <ul id="tags-single">
          <li>Tags:</li>
          {{ range .Params.tags }}
          <li><a href="/tags/{{ . | urlize }}">{{ . }}</a> </li>
          {{ end }}
        </ul>
```

and add 

```
taxonomies:
  tag: tags
```

to `config.yaml`

I could update the docs but figured I would ask first.

Thanks for all the work btw!

**Comment by hossainemruz** [comment]
@alnutile I actually don't know when to use tags 😃. Can you give some use cases?

**Comment by alnutile** [comment]
hey, sure. 
For example I have a blog post that covers both aws and laravel
or aws, laravel, serverless, vuejs etc 

You can see my blog post here  https://alnutile.github.io/posts/333/

This example article will have content about Laravel and about AWS

If you go to https://alnutile.github.io/tags/laravel/ (or click on the tag) it makes a nice display

I use to do this alot here https://alfrednutile.info/ (sadly just noticed the tag link stopped moving ¯\_(ツ)_/¯)
