### ISSUE TITLE
Does search work?

### ISSUE THREAD

**Issue by alnutile** [hugo-toha/guides#35]
I do not see it in the docs and

https://toha-guides.netlify.app/posts/configuration/sections/about-section/
and
https://toha-guides.netlify.app/posts/

do not work

**Comment by hossainemruz** [comment]
We haven't implemented the search feature yet. There is a pending PR here: https://github.com/hugo-toha/toha/pull/88.

I couldn't make it work and didn't get replay from the author.

**Comment by Pistrie** [comment]
Search works correctly now, right? I can't find any info on it in the guides, but I got it working by taking a look at your `config.yaml`

**Comment by hossainemruz** [comment]
Yes.

**Comment by niltied** [comment]
Hi @hossainemruz,

If it works now, then you can close the issue right ?

Regards,

**Comment by hossainemruz** [comment]
Yes. It does work now. Closing this issue.
